package com.example.guide.utils;

import com.example.guide.DB.SceneryDB;
import com.example.guide.bean.Scenery;

import android.app.Application;

/**
 * @author cxm E-mail: 1993baicai@sina.com
 * @date ：2015-7-26 下午2:50:52
 * @version 1.0
 * @parameter
 * @since
 * @return
 */
public class MyApplication extends Application {

	@Override
	public void onCreate() {
		super.onCreate();
		Scenery scenery;
		//江西——南昌景点
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("50" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("南昌之星");
				scenery.setIntroduce("呵呵");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("秋水广场");
				scenery.setIntroduce("呵呵");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("绳金塔");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("50" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("滕王阁");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("八一广场");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("八一起义纪念馆呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("15" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("梅岭");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("35" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("凤凰沟");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("35" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("汪山土库");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("40" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("安义古城");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("八大山人纪念馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("佑民寺");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("江西革命烈士纪念馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("江西省博物馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("洪崖书画院");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("孺子亭");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("翠岩禅寺");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("南昌新四军军部旧址陈列馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("华星陶瓷艺术馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("二十四军指挥部旧址");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("中华奇石精品馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("博美艺术馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("南昌");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("程允贤雕塑艺术馆");
				new SceneryDB(this).insertOneScenery(scenery);
				
				//江西——上饶景点
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("上饶");
				scenery.setLocation("160" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("三清山");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("上饶");
				scenery.setLocation("160" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("婺源");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("上饶");
				scenery.setLocation("70" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("鄱阳湖国家湿地公园");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("上饶");
				scenery.setLocation("80" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("龟峰");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("上饶");
				scenery.setLocation("80" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("神龙宫");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("上饶");
				scenery.setLocation("20" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("鹅湖书院");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("江西");
				scenery.setCity("上饶");
				scenery.setLocation("80" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("神农源");
				new SceneryDB(this).insertOneScenery(scenery);
				
				//北京景点
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("0" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("天安门");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("60" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("故宫");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("60" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("颐和园");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("45" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("八达岭长城");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("50" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("鸟巢");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("20" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("圆明园");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("50" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("中央电视塔");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("10" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("香山公园");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("40" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("恭王府");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("125" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("北京杜莎夫人蜡像馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("50" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("水立方");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("165" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("北京动物园+海洋馆");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("10" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("北海公园");
				new SceneryDB(this).insertOneScenery(scenery);
				scenery = new Scenery();
				scenery.setProvince("北京");
				scenery.setCity("北京");
				scenery.setLocation("100" );
				scenery.setPicUrl(scenery.getProvince() + scenery.getCity() + ".png");
				scenery.setName("明十三陵");
				new SceneryDB(this).insertOneScenery(scenery);
				}
				

			}


